### ISSUE TITLE
from the fog glitched textures

### ISSUE THREAD

**Issue by Robocolin** [DeadbushCarrot/Classicimprovements-issues#1]
when you use from the fog mod the textures for herobrine turn into the deep dark disk fragments i was able to replicate it so that should rule out any other packs i had on
![2024-02-22_02 05 31](https://github.com/DeadbushCarrot/Classicimprovements/assets/160827651/14897e13-c255-4df2-bcc0-56e65d543821)
![2024-02-22_01 57 05](https://github.com/DeadbushCarrot/Classicimprovements/assets/160827651/6f2540bc-13dd-4642-b34f-4fb67e656daf)
![2024-02-22_01 56 55](https://github.com/DeadbushCarrot/Classicimprovements/assets/160827651/7a910f32-335c-46f8-a539-aa81a43556d1)
![2024-02-22_01 54 58](https://github.com/DeadbushCarrot/Classicimprovements/assets/160827651/b547e26e-4020-4092-8e5f-f4989187f5ad)

**Comment by DeadbushCarrot** [comment]
Hey I have read your issue and will be working on a hotfix I did just update CIMS like 7 minutes ago and also THANK YOU FOR USING GITHUB AND SENDING A BUG REPORT Cause your the first one to ever send me one on any of my pages but anyways will be lookin into this!

**Comment by DeadbushCarrot** [comment]
How do you spawn Herobrine in :|

**Comment by DeadbushCarrot** [comment]
@Robocolin 
[Classic Improvements V2.5.1.zip](https://github.com/DeadbushCarrot/Classicimprovements/files/14390475/Classic.Improvements.V2.5.1.zip)
Here the fixed version

**Comment by Robocolin** [comment]
thanks for fixing because this my favorite resource pack I would hate to play without it
