### ISSUE TITLE
1.20.4+ Compatibility ( Classic Improvements ADD ON 6 Glowing ores )

### ISSUE THREAD

**Issue by Nikobu02Gamer** [DeadbushCarrot/Classicimprovements-issues#2]
Hello there!

First off - amazing work on your Programmer Art Emissive Ores pack Deadbush! 
So far, this is the only working pack I've come across that adds emissive textures to the Programmer Art ore textures.

Would you consider adding 1.20.5, 1.20.6+ compatibility ?

As a separate suggestion - would you consider making Netherite / Ancient Debris emissive as well ?

Thank you in advance, and have a good day!

**Comment by DeadbushCarrot** [comment]
Well if it says it incompatible well it is, unless continuity changed anything with how it uses Optifine format
And for the feature request I might make a another pack option for it. Also sorry if am slow to finding these bug reports I barley get any. Edit also forgot to mention that 1.21 is near so getting CIMS ready for the update is highest priority right now!

**Comment by Nikobu02Gamer** [comment]
Thank you for the reply Deadbush!

Looking forward to the 1.21 update! Keep up the good work! :)

**Comment by DeadbushCarrot** [comment]
> Thank you for the reply Deadbush!
> 
> Looking forward to the 1.21 update! Keep up the good work! :)

Hey I added your request to the pack in a separate file

**Comment by Nikobu02Gamer** [comment]
Thank You Carrot!

Can't wait to try the pack out, but sadly waiting for Indium to update, since it's mandatory for Continuity to work with Sodium. 


Keep up the amazing work!
